services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=postgrespwd
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgres/data
  mongodb:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=mongopwd
    ports:
      - 27017:27017
    volumes:
      - mongodata:/var/lib/mongodb/data
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - 5672:5672
      - 15672:15672

  auction-svc:
    image: trycatchlearn/auction-svc:latest
    build:
      context: .
      dockerfile: src/AuctionService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Developpement
      - ASPNETCORE_URLS=http://+80
      - ASPNETCORE_URLS=http://+7777
      - Rabbitmq__Host=rabbitmq
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Username=root;Password=postgrespwd;Database=auction;
      - IdentityServerUrl=http://identity-svc 
      - Kestrel__Endpoints__Grpc__Protocols=Http2
      - Kestrel__Endpoints__Grpc__Url=Http://+:7777
      - Kestrel__Endpoints__WebApi__Protocols=Http1
      - Kestrel__Endpoints__WebApi__Url=Http://+:80
    ports:
      - 7001:80
      - 7777:7777
    depends_on:
      - postgres
      - rabbitmq
  search-svc:
    image: trycatchlearn/search-svc:latest
    build:
      context: .
      dockerfile: src/SearchService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Developpement
      - ASPNETCORE_URL=http://+80
      - Rabbitmq__Host=rabbitmq
      - ConnectionStrings__MongoDbConnection=mongodb://root:mongopwd@mongodb:27017/?authSource=admin&readPreference=primary&ssl=false&directConnection=true
      - AuctionServiceUrl=http://auction-svc 
    ports:
      - 7002:80
    depends_on:
      - mongodb
      - rabbitmq
      - auction-svc
  identity-svc:
    image: trycatchlearn/identity-svc:latest
    build:
      context: .
      dockerfile: src/IdentityServer/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URL=http://+80
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Username=root;Password=postgrespwd;Database=identity;
    ports:
      - 5000:80
    depends_on:
      - postgres
  gateway-svc:
    image: trycatchlearn/gateway-svc:latest
    build:
      context: .
      dockerfile: src/GatewayService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URL=http://+80
    ports:
      - 6001:80
  bid-svc:
    image: trycatchlearn/bid-svc:latest
    build:
      context: .
      dockerfile: src/BiddingService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Developpement
      - ASPNETCORE_URL=http://+80
      - Rabbitmq__Host=rabbitmq
      - ConnectionStrings__BidDbConnection=mongodb://root:mongopwd@mongodb:27017/?authSource=admin&readPreference=primary&ssl=false&directConnection=true
      - IdentityServerUrl=http://identity-svc 
      - GrpcAuction=http://auction-svc:7777 
    ports:
      - 7003:80
    depends_on:
      - mongodb
      - rabbitmq
  
  notify-svc:
    image: trycatchlearn/notify-svc:latest
    build:
      context: .
      dockerfile: src/NotificationService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Developpement
      - ASPNETCORE_URLS=http://+80
      - Rabbitmq__Host=rabbitmq
    ports:
      - 7004:80
    depends_on:
      - rabbitmq

volumes:
  pgdata:
  mongodata: